version: 2
updates:
  - package-ecosystem: npm
    commit-message:
      prefix: 'chore'
      include-scope: true
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    target-branch: main
